### ISSUE TITLE
Re-allow absolute paths

### ISSUE THREAD

**Issue by kikijiki** [nextest-rs/datatest-stable#252]
I use absolute paths for test data stored outside the project directory. The latest update added a restriction that blocks this, without explanation for the change.

Using fixed absolute paths for test data is a common pattern, especially for larger datasets that shouldn't be included in the repository. This worked reliably before the restriction was added.

Would you consider removing this new check? If there are specific concerns that led to blocking absolute paths, please share the context so we can discuss alternatives.

**Comment by sunshowers** [comment]
Ah interesting, thanks for sharing! I removed it because partly there was no test coverage for it, and partly to ensure a consistent UX for things like path separators across platforms.

I'll try putting it back in.

**Comment by sunshowers** [comment]
Released in 0.3.2.

**Comment by kikijiki** [comment]
Thank you!
