### ISSUE TITLE
support look around for regex pattern matching

### ISSUE THREAD

**Issue by webbdays** [nextest-rs/datatest-stable#42]
Use fancy_regex crate instead of standard regex crate.

Thank you very much.

**Comment by sunshowers** [comment]
Thanks for the report! Could you elaborate on your use case? I've used datatest-stable a few times and have never needed anything beyond basic glob-like regexes.

**Comment by webbdays** [comment]
match .md
but not .skip.md

**Comment by sunshowers** [comment]
Done as part of #43 and released in vesion 0.2.7. Thanks again!
