### ISSUE TITLE
How about supporting, skip, only 

### ISSUE THREAD

**Issue by webbdays** [nextest-rs/datatest-stable#45]
Sometimes
developers want to skip some tests files for run and even want to place such test files in codebase skipping tests for them entirely.
or want to just run only one test file to save time.

**Comment by webbdays** [comment]
using fancy_regex was fine for skip.
How about "only" case?

**Comment by webbdays** [comment]
Any idea of fancy regex pattern to support the both?

**Comment by sunshowers** [comment]
Don't quite understand your question, could you provide some concrete examples of what you want to match against?

**Comment by webbdays** [comment]
consider these are test files :
test1.skip.md
test2.md
test3.md
test4.only.md
test5.only.md
test5.skip.md

if we have any test file with .only,md
i.e here we have test4.only.md then
tests runner should run the  first matching only.md i.e test4.only.md

all the .skip.md should be skipped from running and remaining should be run given there isn't atleast one .only.md

**Comment by sunshowers** [comment]
Thanks. I don't think datatest-stable should support that kind of "first matching test" feature -- it's out of its remit.

**Comment by webbdays** [comment]
regex will do.
not the datatest-stable.
harness!(test, root, pattern, only_pattern)
like this.

**Comment by webbdays** [comment]
ok.
I am also realising it as bit off the road.
we should use regex pattern if possible.
Thanks.
